### ISSUE TITLE
codeseed init does not create gitignore files

### ISSUE THREAD

**Issue by swornimbarahi** [sabi1125/CodeSeed#32]
There are no `.gitignore` files created when starting a project with codeseed. I think it's expected to have an autogenerated `.gitignore` file, but an option to not generate it could be useful.

**Comment by sabi1125** [comment]
This will be fixed in the following ticket.

https://github.com/sabi1125/CodeSeed/pull/34

**Comment by sabi1125** [comment]
fixed in the following ticket
https://github.com/sabi1125/CodeSeed/pull/34
